zuul:
  routes:
    api:
      url: "http://nodejs-srv:3000"

ribbon:
  eureka:
    enabled: false

server:
  port: 8080

spring:
  application:
    name: "zipnik-sleuth-site1"
  zipkin:
    baseUrl: "http://zipkin-srv:9411"
